spring:
  application:
    name: eureka-server
  cloud:
    vault:
      #      uri: http://host.docker.internal:8200
      uri: http://vault:8200
      kv:
        enabled: false
        backend: secret
        default-context: example
  profiles:
    active: dev
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false   # Server doesn’t register itself
    fetch-registry: false         # Server doesn’t fetch other registries
  server:
    waitTimeInMsWhenSyncEmpty: 0  # Faster startup
    enableSelfPreservation: false # Disable for development; enable in production
  instance:
    prefer-ip-address: false
    hostname: serviceregistry
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
