spring:
  application:
    name: eureka-server
  cloud:
    vault:
      #      uri: http://host.docker.internal:8200
      uri: http://vault:8200
      kv:
        enabled: false
        backend: secret
        default-context: example
  profiles:
    active: dev
eureka:
  client:
    register-with-eureka: false   # Server doesn’t register itself
    fetch-registry: false         # Server doesn’t fetch other registries
  server:
    waitTimeInMsWhenSyncEmpty: 0  # Faster startup
    enableSelfPreservation: false # Disable for development; enable in production
  instance:
    prefer-ip-address: true
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
management:
  endpoints:
    web:
      base-path: /api/events/serviceregistry/actuator
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

