server:
  port: 9002
brokers: kafka:9092
spring:
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      password: MyStrongPassword
  datasource:
    url: jdbc:mariadb://157.20.214.83:3306/appdb
    username: appuser
    password: App@12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    username: atulrathodc@gmail.com
    password: "fvpm xuzo kdyu wldi"
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    charset: UTF-8
    expose-spring-macro-helpers: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: hvs.TBbcfeYxzpH8yXRTvZtQJjeJ
      kv:
        enabled: true
        backend: secret
        default-context: example

logging:
  level:
    org:
      springframework:
        security: DEBUG

support:
  email: atulrathodc@gmail.com
  name: Atul Rathod

stripe:
  secret:
    key: sk_test_XXXXXXXXXXXXXXXXXXXX

openai:
  model: gpt-4o-mini
  api:
    key: sk-svcacct-IV3H3npvGdyco2RPOQD2jLZx4vtPSDenb-nSoHeBCCrzSyHA1pS3Loi-gKowfOT3BlbkFJHIW8ui5Y43Xz_iU3gO7vI5XnSH4PMrlO-8uX9DIUDtUC2LpRTO532KeVyitQMA
    url: https://api.openai.com/v1/chat/completions

my:
  framework:
    enabled: true
    apiKey: abc-123-secret

management:
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /actuator

resilience4j:
  circuitbreaker:
    instances:
      myService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      myService:
        maxAttempts: 3
        waitDuration: 2s

